### ISSUE TITLE
Update to .NET Aspire Preview 5 stopped running projects in AppHost

### ISSUE THREAD

**Issue by EarlJester** [rafaelldi/aspire-plugin#109]
I have update my  .NET Aspire version to Preview 5 and plugin starting AppHost with  **Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler** iterated.
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/9df5fa8e-7fd6-472e-8ba3-4f8487f13c8d)
If I start the AppHost without using the plugin, it work fine. 
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/836208de-600a-4340-af7d-4ccdb6a87ceb)
I think Aspire have changed API for connection in latest version, and plugin can`t connect to AppHost and start work.
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/566d4950-054a-4ad6-935b-3cdb0d266dd7)

**Comment by rafaelldi** [comment]
Hi! Thanks! I'm already working on the next version. Will be available in a few days

**Comment by arif-hanif** [comment]
@rafaelldi thanks for the update

**Comment by EarlJester** [comment]
Changelog.md:

Changed
https://github.com/rafaelldi/aspire-plugin/issues/109: Support for .NET Aspire preview 4

But its Preview 5 =)

**Comment by EarlJester** [comment]
@rafaelldi i have same problem, maybe it's not cause Preview 5?
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/cd2e6a7b-bd70-4363-a579-007f906ccbaf)
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/c37edac7-8a67-41c4-b244-10b36743d5b3)

**Comment by rafaelldi** [comment]
@EarlJester 

> But its Preview 5 =)

I was in a rush to make a new version. Thank you!

> i have same problem, maybe it's not cause Preview 5?

Quite strange environment variables. Are they generated in this way?

**Comment by EarlJester** [comment]
Yep, i specially recreate run configuration "Unnamed" for test purpose, and change only Build Project -> Build Solution

**Comment by EarlJester** [comment]
Its good idea, to clean variables. Now dashboard running, but not starts Microservice
And i don't know why its starts on http://localhost:18888
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/bf5032aa-a8ec-48ba-b989-ef1d438feec2)

**Comment by rafaelldi** [comment]
It starts on `18888` port because that is the default one. If you want something different, you can use `ASPNETCORE_URLS: http://localhost:15162` something like that. Is the Aspire dashboard also empty?

**Comment by EarlJester** [comment]
Yes, Aspire dashboard empty
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/503f9380-19b1-48b7-82f9-4a1f0cc0f515)

**Comment by rafaelldi** [comment]
Also, there should be another environment variable `"DOTNET_RESOURCE_SERVICE_ENDPOINT_URL": "http://localhost:20091"`

**Comment by EarlJester** [comment]
Yep, now its all working. Here last variables and config
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/a9253f7b-e3da-4830-b965-762cd7452ac5)
@rafaelldi thanks for your patience and help)
And for your plugin is great!
