### ISSUE TITLE
After starting the Aspire configuration, nothing happens

### ISSUE THREAD

**Issue by rafaelldi** [rafaelldi/aspire-plugin#111]

**Comment by rafaelldi** [comment]
This bug seems to be introduced in the latest release. As a quick fix, you can remove a `Build Project` BeforeLaunchTask and add a `Build Solution` one.

<img width="790" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/16965141/7c170e43-c2a8-478b-a19f-6d7d265341f1">

**Comment by ondrejpialek** [comment]
I can confirm that the workaround works, thank you!
