### ISSUE TITLE
Aspire project doesn't start after upgrading to Rider 2024 and Aspire Preview 5

### ISSUE THREAD

**Issue by dotnetian** [rafaelldi/aspire-plugin#115]
When I make a blank Aspire project, it launches successfully. But when I try to run my upgraded Aspire-based project, it just does nothing.

https://github.com/rafaelldi/aspire-plugin/assets/70327745/e5bf02c9-ea2a-44fa-9756-fd9c7ae82a8a

**Comment by rafaelldi** [comment]
You need to change the BeforeRunTask (see #111)
