### ISSUE TITLE
Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0] - failed to set output writers to capture stdout/stderr

### ISSUE THREAD

**Issue by maartenba** [rafaelldi/aspire-plugin#125]
Issue from the .NET Evolution Discord:

> Hey everyone, did replicas break in the new release? Apphost is breaking with the following error:
> ```
> Aspire.Hosting.Dcp.dcpctrl.ExecutableReconciler[0]
>      failed to set output writers to capture stdout/stderr     {"Executable": {"name":"api-b0ldos8"}, "Reconciliation": 3, "error": "target writer already set"}
> ```
> 
> Code is:
> ```
> var builder = DistributedApplication.CreateBuilder(args);
> 
> var db = builder
>     .AddSqlServer("db")
>     .AddDatabase("dbdata");
> 
> builder
>     .AddProject<Projects.Api>("api")
>     .WithReference(db)
>     .WithHttpsEndpoint(65001)
>     .WithReplicas(3);
> 
> builder.Build().Run();
> ```

To repro the issue, run the attached AppHost project: [AppHost1.zip](https://github.com/rafaelldi/aspire-plugin/files/15108865/AppHost1.zip)

**Comment by karolz-ms** [comment]
From looking at the Aspire orchestrator sources (haven't tried with Rider/plugin yet, sorry), this error occurs most likely because the plugin returns the same run ID for two different executions of the same project/replica.
