### ISSUE TITLE
Multiple replicas of API Service Will Not Launch

### ISSUE THREAD

**Issue by napalm684** [rafaelldi/aspire-plugin#132]
In .NET Aspire preview 5 and 6 the following behavior was observed with the starter template project with the following modification inside the AppHost `Program.cs` file:

```
var apiService = builder.AddProject<Projects.AspireApp3_ApiService>("apiservice")
    .WithReplicas(2);
```

Behavior:

Neither instance of the `apiservice` becomes available and sometimes the solution debug session crashes. There are no logs in the dashboard reported either.

![image](https://github.com/rafaelldi/aspire-plugin/assets/8197405/c55b2fee-a10b-4ead-8051-456207695d9f)

See https://github.com/dotnet/aspire/discussions/3818#discussioncomment-9232087 for discussion with Microsoft.

**Comment by rafaelldi** [comment]
Thank you. This is already fixed (see: https://github.com/rafaelldi/aspire-plugin/issues/125)

**Comment by napalm684** [comment]
Has this been released? I installed preview 6 version of plugin today with no success fixing issue.

**Comment by rafaelldi** [comment]
Not yet. I plan to release it next week

**Comment by napalm684** [comment]
Thank you I can confirm this is fixed!
