### ISSUE TITLE
.NET Aspire run/debug configurations do not respect associated launch profile?

### ISSUE THREAD

**Issue by philliphoff** [rafaelldi/aspire-plugin#177]
For a .NET Aspire host project, suppose I have two launch profiles `ProfileA` and `ProfileB` in `launchSettings.json`, where each profile uses a different set of command line arguments (`commandLineArgs`).  I then have two .NET Aspire run/debug configurations `AspireA` and `AspireB`, where each is associated with their respective launch profile.  When I select and run/debug using the .NET Aspire configuration, the .NET Aspire host project does not appear to get the command line arguments of its associated launch profile, nor the other.  That is, it appears that the launch profiles are ignored altogether.

If I select and run/debug one of the launch profiles for the .NET Aspire host project directly, the project is started using the selected set of command line arguments.

Is the .NET Aspire run/debug configuration *supposed* to launch the host project with the associated launch profile?  If so, are there logs I can use to help understand why this doesn't seem to be happening?  (I didn't see anything in the IDE logs.  I see the same issue even if I have just a single launch profile and a single .NET Aspire run/debug configuration; the configuration doesn't seem to launch the host project using the profile settings.)

Plugin version: 1.0.1

**Comment by rafaelldi** [comment]
Hello! `commandLineArgs` is not supported for the host project configurations, but I can support it

**Comment by philliphoff** [comment]
@rafaelldi Just updated the plugin and multiple profiles (with different command line arguments) works like a charm. Thanks for the quick turnaround!
