### ISSUE TITLE
Aspire option not showing in Ubuntu 24.04

### ISSUE THREAD

**Issue by plankman2k** [rafaelldi/aspire-plugin#193]
Hi there, not sure if this is the correct place to put this. I'm running Rider 2024.1.4 on Ubuntu 24.04. I have .Net 8 installed, the Aspire workload is installed, Docker Desktop is installed and running and I have the Aspire plugin installed in Rider. When I go to create a new project, I don't see Aspire as an option. I can create an Aspire project from CLI and open it in Rider, like this if I right-click on the AppHost project it gives me the option to generate the Aspire manifest, so it is seeing part of the plugin. Is this a bug or have I missed something?

![image](https://github.com/rafaelldi/aspire-plugin/assets/1969702/bf9e6b14-e3e4-4ade-ab45-faa2e806b753)

**Comment by rafaelldi** [comment]
Hello! This part comes from the Rider itself, not the plugin. Could you please create an issue in our tracker https://youtrack.jetbrains.com/issues/RIDER. My colleagues will take a look at it.
