### ISSUE TITLE
Fails to Update Workload on macOS

### ISSUE THREAD

**Issue by khalidabuhakmeh** [rafaelldi/aspire-plugin#23]
![JetBrains Rider -2023-12-29 -12-37-48](https://github.com/rafaelldi/aspire-plugin/assets/228256/bf99d6e7-49f9-4412-a1aa-99eb9347b68b)

I would upload the logs here, but there might be sensitive environment variables in the logs.

## Update

I think this is an issue with `sudo` on macOS and Linux. Workloads need to use `sudo dotnet workload update aspire` and escalate to administrator.

**Comment by rafaelldi** [comment]
@khalidabuhakmeh Thank you Khalid. I'll check

**Comment by khalidabuhakmeh** [comment]
Awesome!
