### ISSUE TITLE
Ignores standard well known environment variables in launchSettings.json

### ISSUE THREAD

**Issue by JohnGalt1717** [rafaelldi/aspire-plugin#24]
VS.net works fine with the following and the path is correct:

			"environmentVariables": {
				"ASPNETCORE_ENVIRONMENT": "Development",
				"DOTNET_ENVIRONMENT": "Development",
				"DOTNET_DASHBOARD_OTLP_ENDPOINT_URL": "http://localhost:7064",
				"DEV_PATH": "$(MSBuildProjectDirectory)/../.dev",
				"CERTIFICATE_PATH": "$(MSBuildProjectDirectory)/../.dev/certificates",
				"CONFIG_PATH": "$(MSBuildProjectDirectory)/../Configuration"
			}

Rider is fine with those same types of configs in each of the individual services that are run if they're run by themselves.

But Rider with the host running, doesn't get the right pathing for the host. It appears to ignore the value of $(MSBuildProjectdirectory) which is null when dumped to the console in the host, but not if I run it from vs.net or run any of the services separately in rider.

In fact, it appears that the standard environment variables aren't set at all and don't get passed into the services launched either.

This is a blocker for us.

**Comment by rafaelldi** [comment]
Thank you, I'll add environment variables to the Aspire Host run configuration.

**Comment by JohnGalt1717** [comment]
FYI, this isn't fixed as of the update that says that it is.  $(MSBuildProjectDirectory) is not being replaced in the environment variables. It should be pulling the full path.

Here's an exact example that VS.net replaces properly: 

"CONFIG_PATH": "$(MSBuildProjectDirectory)/../configuration",

**Comment by rafaelldi** [comment]
@JohnGalt1717 Sorry, I misunderstood your request. I added this replacement only for the Aspire Host project. I will add this substitution for other projects as well.
