### ISSUE TITLE
Issue with Dapr while project started from aspire-plugin

### ISSUE THREAD

**Issue by laurentkempe** [rafaelldi/aspire-plugin#28]
I am using the following project [DaprOutbox](https://github.com/laurentkempe/aspirePlayground/tree/main/DaprOutbox).

When I use the Aspire Host run configuration added by the plugin to run, I see the following issues in the console logs of webfrontend-dapr and/or subscriber-dapr:

```
time="2024-01-05T15:21:19.0975586+01:00" level=warning msg="failed to subscribe to topics: error occurred while beginning pubsub pubsub: Get \"http://127.0.0.1:5203/dapr/subscribe\": read tcp 127.0.0.1:63905->127.0.0.1:5203: wsarecv: An existing connection was forcibly closed by the remote host. " app_id=subscriber-dapr instance=Beast scope=dapr.runtime type=log ver=1.12.2
``` 

When I run using the .NET Launch Settings Profile; DaprOutbox.AppHost: http then everything works fine but then I don't have access to all features provided by your plugin.

**Comment by rafaelldi** [comment]
@laurentkempe Thank you for the issue! I tried running your example on my machine, and I don't see the `failed to subscribe to topics` error in the dashboard logs (there is `msg="app is subscribed to the following topics: [Counter] through pubsub=pubsub"` message instead). How can I verify that everything is working correctly on my side? Maybe I missed some steps to reproduce your problem correctly?

**Comment by laurentkempe** [comment]
Welcome, thanks for having a look @rafaelldi 
Have a look to both Console Logs of webfrontend-dapr and subscriber-dapr
![image](https://github.com/rafaelldi/aspire-plugin/assets/272612/477749f5-383b-4c62-a643-db81a66590de)

Sometime both, some other time one shows the error
![image](https://github.com/rafaelldi/aspire-plugin/assets/272612/1a12cc3b-5138-4150-a8b4-cb23062f3955)

> How can I verify that everything is working correctly on my side? Maybe I missed some steps to reproduce your problem correctly?

Navigate to http://localhost:5172/counter and click count

Then from Aspire dashboard navigate to the console log / subscriber and you should see an output like the following one (please pull latest changes from this repo before)
![image](https://github.com/rafaelldi/aspire-plugin/assets/272612/dfa926cc-46c2-4895-b9a5-61bc0ebcbe52)

**Comment by laurentkempe** [comment]
FYI @rafaelldi I downgraded to each version of the plugin and got the same issue for all versions. I am sure I had it working in the past. So, it might come from an external problem. I still don't see why it works when I do a `dotnet run --project .\DaprOutbox.AppHost\DaprOutbox.AppHost.csproj`.

**Comment by rafaelldi** [comment]
@laurentkempe Just tried again to reproduce, and I see the counters in the subscriber log. Maybe there is something in your environment?

<img width="467" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/16965141/69d057fb-9e85-4490-a048-00ba0a377a9b">

**Comment by laurentkempe** [comment]
@rafaelldi Did you run in debug?

**Comment by rafaelldi** [comment]
No, it was Run. Under Debug, I have the same problem. Thank you, going to investigate it.

**Comment by rafaelldi** [comment]
@laurentkempe Please, try with the disabled DPA plugin. It works on my side, if it works for you, I will think how to fix the problem properly.

<img width="738" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/16965141/3a88db45-1d6f-4132-bd0a-3d20353c8cb0">

**Comment by laurentkempe** [comment]
I will try when I get access to a PC later

**Comment by laurentkempe** [comment]
@rafaelldi I turned off DPA and it works 🎉 👍🏼 

<img width="230" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/272612/6182dbc1-8d6b-47d1-9ebc-28ad22984233">

I still get the error but the retry policy fixes it then

<img width="1600" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/272612/cf1924c4-8a7d-45cf-8d93-438ade6f4a1c">

I think you can close that issue now, what do you think?

**Comment by rafaelldi** [comment]
Cool, thank you! Then we'll think how to fix it without disabling DPA.

**Comment by laurentkempe** [comment]
Good news @rafaelldi I have tried with a nightly build of preview 3 and all works with the plugin 🎉 even with DPA enabled, so the issue was not coming from the plugin 🥇
