### ISSUE TITLE
Dapr sidecars do not successfully connect to pubsub component.

### ISSUE THREAD

**Issue by aladd04** [rafaelldi/aspire-plugin#50]
Error log from my dapr sidecars, note I'm ommitting computer/app specific values:

```
time="2024-01-26T11:50:06.496542-05:00" level=warning msg="failed to subscribe to topics: error occurred while beginning pubsub {{PUB_SUB_NAME}}: Get \"http://127.0.0.1:5034/dapr/subscribe\": read tcp 127.0.0.1:60618->127.0.0.1:5034: read: connection reset by peer " app_id={{APP_ID}} instance={{INSTANCE_ID}} scope=dapr.runtime type=log ver=1.12.4
```

This only happens when running with this plugin. I'm on version `2023.3.3` of Rider and on MacOS version `14.3`. My dapr CLI version is `1.12.0` and runtime version is `1.12.4`. If I run the app via `dotnet run` on the command line, pubsub works fine. So I'm guessing it's something within this plugin or Rider.

**Comment by rafaelldi** [comment]
Hello! It's an Aspire bug, please see this issue #28 (in the next preview 3 it should be fixed). You can turn off the DPA plugin, it should help.

**Comment by rafaelldi** [comment]
Thank you for the report!
