### ISSUE TITLE
Shift F5 not stopping all instances, hot reload is not supported via DCP.

### ISSUE THREAD

**Issue by attilah** [rafaelldi/aspire-plugin#65]
I've a Preview 3, when I F5 run the solution debugging works. With Shift+F5 processes are stopping but not the AppHost.

If I make a Hot reload compatible change and hit "Apply" in rider, the given process is not reloaded, so I've to stop everything, and re-run.

**Comment by rafaelldi** [comment]
Hello! Sorry for the late reply. I made some changes in the latest release. Now Hot Reload in debugging (aka Edit and Continue) should work. As for the first problem, that should also be fixed.
