### ISSUE TITLE
Builds do not work properly after modifying the Solution

### ISSUE THREAD

**Issue by dotnetian** [rafaelldi/aspire-plugin#68]
Hello,

I'm writing to report an issue I've encountered with the .NET Aspire plugin for Rider. The plugin was functioning perfectly on my Windows 11 machine, detecting all projects, running them, and attaching the debugger as required. However, when I attempted to open the project on a Linux PC, I ran into several errors due to the use of "\\" in path strings and case sensitivity issues with paths. After updating the project files, I was able to run the project on Linux.

Upon returning to my Windows machine, pulling the changes, and running the project, I found that only one project was successful. The AppHost was built and running, but out of all the projects, only one ran. I noticed that reverting to the commits before the Linux changes resolved the issue. Interestingly, when I run the AppHost with .NET CLI, all projects are built and run successfully. I've tried to capture the build logs but found no errors.

I'm unsure why this is happening or what the exact issue is. Any assistance would be greatly appreciated.

Thank you.

**Comment by rafaelldi** [comment]
Hi!

>  I ran into several errors due to the use of "\" in path strings and case sensitivity issues with paths.

Do you mean paths in the Aspire host project references `builder.AddProject("...","...");`?

You could try to remove the child run configurations, Rider will regenerate it.

<img width="830" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/16965141/ef737f38-6361-421e-acca-06b3644c4e8a">
