### ISSUE TITLE
Latest version - launchsettings.json relative pathing to $(MSBuildProjectDirectory) one deeper only when debugging host

### ISSUE THREAD

**Issue by JohnGalt1717** [rafaelldi/aspire-plugin#92]
Something happened in the latest version, because this is now the wrong directory compared to what it would be if you debugged the service directly. It's once deeper that it should be as thus all of the launchsettings.json files for every service are wrong and you can't debug host, and debug the service by itself without having to change the profile's pathing for environment variables.

**Comment by rafaelldi** [comment]
I'm not sure I fully understand your problem. Could you please provide a sample application demonstrating a potential bug?

**Comment by JohnGalt1717** [comment]
For whatever reason if you make a path relative to that environment variable, it has a different depth with this plugin than if you use dotnet run. I.e. you can't have one configuration that is used for Aspire AND for dotnet run for things like FastEndpoints Swagger generation. They're different depending on how it's run.

**Comment by rafaelldi** [comment]
Hello @JohnGalt1717. I've made some changes in the latest v0.5.0 release. Please check if it works for you.
